-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 20:47:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DER` DEFAULT CHARACTER SET utf8 ;
USE `DER` ;

-- -----------------------------------------------------
-- Table `DER`.`Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Proceso` (
  `idProceso` INT NOT NULL AUTO_INCREMENT,
  `generalVenta` TINYINT NULL,
  `agregarEquipoNuevo` TINYINT NULL,
  `consultarProductos` TINYINT NULL,
  PRIMARY KEY (`idProceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`PermisosPorRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`PermisosPorRoles` (
  `idPermisos Por Roles` INT NOT NULL AUTO_INCREMENT,
  `idProceso` INT NULL,
  `idRol` INT NULL,
  `fechaVencimiento` DATE NULL,
  PRIMARY KEY (`idPermisos Por Roles`),
  INDEX `fk_proceso_idx` (`idProceso` ASC),
  INDEX `fk_rol_idx` (`idRol` ASC),
  CONSTRAINT `fk_proceso`
    FOREIGN KEY (`idProceso`)
    REFERENCES `DER`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `DER`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` INT NULL,
  `mail` VARCHAR(45) NULL,
  `dni` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `permisos` INT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_permisos_idx` (`permisos` ASC),
  CONSTRAINT `fk_permisos`
    FOREIGN KEY (`permisos`)
    REFERENCES `DER`.`PermisosPorRoles` (`idPermisos Por Roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`TiposDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`TiposDePago` (
  `idTiposDePago` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoDePago` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTiposDePago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`TiposDeEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`TiposDeEnvio` (
  `idTiposDeEnvio` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoEnvio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTiposDeEnvio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombrePais` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombreProvincia` VARCHAR(45) NULL,
  `pais` INT NULL,
  PRIMARY KEY (`idProvincia`),
  INDEX `fk_pais_idx` (`pais` ASC),
  CONSTRAINT `fk_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `DER`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `nombreLocalidad` VARCHAR(45) NULL,
  `codigoPostal` INT NULL,
  `provincia` INT NULL,
  PRIMARY KEY (`idLocalidad`),
  INDEX `fk_provincia_idx` (`provincia` ASC),
  CONSTRAINT `fk_provincia`
    FOREIGN KEY (`provincia`)
    REFERENCES `DER`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Estado` (
  `idEstado` INT NOT NULL,
  `nombreEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpresa` VARCHAR(50) NULL,
  `fechaVenta` DATETIME NULL,
  `numeroVenta` INT NULL,
  `idCliente` INT NULL,
  `tiposPago` INT NULL,
  `descuento` DOUBLE NULL,
  `tiposEnvio` INT NULL,
  `direccionEnvio` VARCHAR(50) NULL,
  `localidad` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_cliente_idx` (`idCliente` ASC),
  INDEX `fk_tiposPago_idx` (`tiposPago` ASC),
  INDEX `fk_tiposEnvio_idx` (`tiposEnvio` ASC),
  INDEX `fk_localidad_idx` (`localidad` ASC),
  INDEX `fk_estado_idx` (`estado` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `DER`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiposPago`
    FOREIGN KEY (`tiposPago`)
    REFERENCES `DER`.`TiposDePago` (`idTiposDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiposEnvio`
    FOREIGN KEY (`tiposEnvio`)
    REFERENCES `DER`.`TiposDeEnvio` (`idTiposDeEnvio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_localidad`
    FOREIGN KEY (`localidad`)
    REFERENCES `DER`.`Localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `DER`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombreMarca` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `razonSocial` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `localidad` INT NULL,
  `contacto` INT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `nombreEquipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `categoria` INT NULL,
  `marca` INT NULL,
  `precio` FLOAT NULL,
  `tamañoPantalla` INT NULL,
  `discoDuro` INT NULL,
  `stockDisponible` INT NULL,
  `proveedor` INT NULL,
  `estaEnOferta` TINYINT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `fk_categoria_idx` (`categoria` ASC),
  INDEX `fk_marca_idx` (`marca` ASC),
  INDEX `fk_proveedor_idx` (`proveedor` ASC),
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `DER`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marca`
    FOREIGN KEY (`marca`)
    REFERENCES `DER`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`proveedor`)
    REFERENCES `DER`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`DetalleVenta` (
  `idDetalleVenta` INT NOT NULL AUTO_INCREMENT,
  `idVenta` INT NOT NULL,
  `equipo` INT NOT NULL,
  `oferta` FLOAT NOT NULL,
  `cantidad` INT NULL,
  `precioConOferta` FLOAT NULL,
  PRIMARY KEY (`idDetalleVenta`, `idVenta`),
  INDEX `fk_equipo_idx` (`equipo` ASC),
  INDEX `fk_venta_idx` (`idVenta` ASC),
  CONSTRAINT `fk_equipo`
    FOREIGN KEY (`equipo`)
    REFERENCES `DER`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `DER`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`Sesion` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NULL,
  `fechaInicio` DATE NULL,
  `horaInicio` DATE NULL,
  PRIMARY KEY (`idSession`),
  INDEX `fk_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `DER`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `DER` ;

-- -----------------------------------------------------
-- Placeholder table for view `DER`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `DER`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DER`.`view1`;
USE `DER`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
